# Generated by Django 4.2.6 on 2023-11-01 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=1000)),
                ('rating', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('price_range', models.FloatField(max_length=500)),
                ('special_request', models.CharField(max_length=500)),
                ('job_type', models.ManyToManyField(to='base.job')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('sender', models.CharField(max_length=50)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=1000)),
                ('rating', models.FloatField(max_length=5)),
                ('cv', models.FileField(upload_to='files')),
                ('assigned_work', models.ManyToManyField(to='base.job')),
                ('client_reviews', models.ManyToManyField(to='base.review')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.worker')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.consumer')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.problem')),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='basket',
            field=models.ManyToManyField(to='base.problem'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
