# Generated by Django 4.2.6 on 2023-11-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_problem_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='job_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.job'),
        ),
    ]
