# Generated by Django 4.2.6 on 2023-11-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_problem_job_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ('rating',)},
        ),
        migrations.AddField(
            model_name='reciept',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
