# Generated by Django 4.2.6 on 2023-11-04 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_worker_options_reciept_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=20000)),
                ('bids', models.BooleanField(default=False)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.worker')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.problem')),
            ],
            options={
                'ordering': ('value',),
            },
        ),
    ]
