# Generated by Django 4.2.6 on 2023-11-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_bids_bids_remove_worker_assigned_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='cv',
            field=models.FileField(upload_to='files/'),
        ),
    ]
