# Generated by Django 4.2.6 on 2023-11-11 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_consumer_basket_problem_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.worker'),
        ),
    ]
