# Generated by Django 4.2.6 on 2023-11-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_job_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='workers',
        ),
        migrations.AddField(
            model_name='job',
            name='workers',
            field=models.ManyToManyField(null=True, to='base.worker'),
        ),
    ]
