# Generated by Django 4.2.6 on 2023-11-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_job_workers_job_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='workers',
            field=models.ManyToManyField(to='base.worker'),
        ),
    ]
