# Generated by Django 4.2.6 on 2023-11-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_notifications_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='price',
            field=models.FloatField(default=0, max_length=1250),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
