# Generated by Django 4.2.6 on 2023-11-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_reciept_price_alter_notifications_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
