# Generated by Django 4.2.6 on 2023-12-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_problem_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='job',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='reciept',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='reciept',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='reciept',
            name='work',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='client_reviews',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Reciept',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
