# Generated by Django 4.2.6 on 2024-01-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
