# Generated by Django 4.2.6 on 2024-01-26 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0032_category_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='users',
        ),
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
