# Generated by Django 4.2.6 on 2024-01-26 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_profile_followers_alter_category_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='users',
        ),
    ]
