# Generated by Django 4.2.6 on 2024-01-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_category_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
    ]
