# Generated by Django 4.2.6 on 2024-01-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_category_chat_vote_votegroup_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(blank=True, to='base.profile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(blank=True, to='base.profile'),
        ),
    ]
