# Generated by Django 4.2.6 on 2024-01-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_category_users_alter_chat_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=1250),
        ),
    ]
