# Generated by Django 4.2.6 on 2024-01-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='includeVotes',
            field=models.BooleanField(default=False),
        ),
    ]
