# Generated by Django 4.2.6 on 2024-01-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_profile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_count',
            field=models.IntegerField(default=0),
        ),
    ]
