# Generated by Django 4.2.6 on 2024-01-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_profile_chat_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='liked_by',
            field=models.ManyToManyField(blank=True, to='base.profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
