# Generated by Django 4.2.6 on 2024-01-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_message_liked_by_message_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='room',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='total',
        ),
        migrations.AddField(
            model_name='votegroup',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
